codecov: 
  notify: 
    require_ci_to_pass: true
comment: 
  behavior: default
  layout: "header, diff"
  require_changes: false
coverage: 
  precision: 1
  range: 95...100
  round: down
  status: 
    changes: false
    patch: 
      production: 
        target: 30%
    project: 
      production: 
        target: 50%
parsers: 
  gcov: 
    branch_detection: 
      conditional: true
      loop: true
      macro: false
      method: false
