codecov: 
  notify: 
    require_ci_to_pass: true
comment: 
  behavior: spammy
  layout: "header, diff"
  require_changes: false
coverage: 
  precision: 1
  range: "95...100"
  round: down
  status: 
    changes: false
    patch: 
      backend: 
        flags: backend
        target: 30%
      frontend: 
        flags: frontend
        target: 20%
    project: 
      backend: 
        flags: backend
        target: 50%
      frontend: 
        flags: frontend
        target: 40%
flags: 
  backend: 
    paths: 
      - Calculator/
  frontend: 
    paths: 
      - FrontEnd/
  tests: 
    paths: 
      - CalculatorTests/
parsers: 
  gcov: 
    branch_detection: 
      conditional: true
      loop: true
      macro: false
      method: false
