codecov: 
  notify: 
    require_ci_to_pass: true
comment: 
  behavior: spammy
  layout: header, diff
  require_changes: false
coverage: 
  precision: 1
  range: 95...100
  round: down
  status: 
    changes: false
    patch: 
      frontend: 
        target: 20%
        flags: frontend
      backend:
        target: 30%
        flags: backend
    project: 
      frontend: 
        target: 40%
        flags: frontend
      backend:
        target: 50%
        flags: backend
parsers: 
  gcov: 
    branch_detection: 
      conditional: true
      loop: true
      macro: false
      method: false
flags:
  # filter the folder(s) you wish to measure by that flag
  backend:
    # only include files in the backend folder
    paths:
      - Calculator/
  frontend:
    paths:
      - FrontEnd/
  tests:
    paths:
      - CalculatorTests/
