codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: 50...70

  status:
    project: yes
      target: 60%
    patch: yes
      target: 50%
    changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
