codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: 95...100

  status:
    project:
      production:
        target: 50%
      test:
        target: 40%

    patch:
      production:
        target: 30%
      test:
        target: 40%

    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, trends, uncovered"
  behavior: spammy
  require_changes: no
